### PR TITLE
deploy und:puppet off of current

### PR DESCRIPTION
**Pull request by msuhovec**
#issue-40

### CODE REVIEW

**Comment by dbrower** [comment]
What is the problem with the old code? Why isn't `release_path` what we want?

**Comment by msuhovec** [comment]
I don't know- I think $release_path should work, but it sometimes fails.

**Comment by dbrower** [comment]
Did you say something earlier that the wrong version of something was being deployed?

**Comment by dbrower** [comment]
Mark, if you've traced down the root cause to this, go ahead and merge.

As we discussed in person, it seems strange that the `release_path` only causes problems some of the time. I feel there is more to the problem.

**Pull request merged**
